[package]
name = "tristate"
description = "A three-valued type equivalent to Option<bool>."
license = "MIT/Apache-2.0"
version = "0.0.2"
authors = ["Dave Herman <dherman@mozilla.com>"]
documentation = "https://docs.rs/tristate"
repository = "https://github.com/dherman/tristate"

[dependencies]
